# we need trusty for the chrome addon
dist: trusty

# we don't need sudo, so can run in a container, which makes startup much
# quicker.
#
# unfortunately we do temporarily require sudo as a workaround for
# https://github.com/travis-ci/travis-ci/issues/8836
sudo: required

language: node_js
node_js:
    - node # Latest stable version of nodejs.
install:
    - ./scripts/travis/install-js-sdk.sh
    - ./scripts/travis/install-react-sdk.sh

addons:
  chrome: stable

cache:
  npm: true
  directories:
    - "$HOME/.npm"
    - "$HOME/nm-cache"

matrix:
    include:
        - name: Linting Checks
          script:
            # run the linter, but exclude any files known to have errors or warnings.
            - npm run lintwithexclusions
        - name: Unit Tests
          script:
            - npm run test
        - name: Riot-web Unit Tests
          install:
            - ./scripts/travis/install-js-sdk.sh
            - ./scripts/travis/install-react-sdk.sh
            - ./scripts/travis/install-riot-web.sh
          script:
            - ./scripts/travis/riot-unit-tests.sh
        - name: End-to-End Tests
          if: branch = develop
          install:
            - sudo apt-get install build-essential python2.7-dev libffi-dev python-pip python-setuptools sqlite3 libssl-dev python-virtualenv libjpeg-dev libxslt1-dev
          script:
            - ./scripts/travis/end-to-end-tests.sh
